# 使用语言
language: hugo
# hugo版本
hugo: stable
# 设置只监听哪个分支
branches:
  only:
  - source
  
sudo: true
dist: trusty

before_install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
  - git config --global user.name "fydy"
  - git config --global user.email "edu@yuns.me"

script:
- /snap/bin/hugo --theme=hugo-universal-theme --baseUrl="https://luolvshi.me/hugo/"

after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://$hugo@github.com/fydy/hugo.git
  master
